version: '3'
services:
#    openhab:
#        image: openhab/openhab:2.5.1
#        restart: always
#        #network_mode: host
#        volumes:
#            - /etc/localtime:/etc/localtime:ro
#            - /etc/timezone:/etc/timezone:ro
#            - ./config/openhab/addons:/openhab/addons
#            - ./data/openhab/openhab_conf:/openhab/conf
#            - ./data/openhab/userdata:/openhab/userdata
#        environment:
#            #OPENHAB_HTTP_PORT: 8080
#            #OPENHAB_HTTPS_PORT: 8443
#            EXTRA_JAVA_OPTS: -Duser.timezone=Europe/Moscow
    postgres:
        image: postgres:9.6.16
        restart: always
        volumes:
            - /mnt/raid1/postgres:/var/lib/postgresql/data
        env_file:
            - ./db.env
        networks:
            - backend
    nextcloud:
        image: nextcloud:20.0.1-apache
        restart: always
        volumes:
            - /mnt/raid1/nextcloud:/var/www/html
        depends_on:
            - postgres
        environment:
            POSTGRES_HOST: postgres
            OVERWRITEWEBROOT: /nextcloud
        env_file:
            - ./db.env
        networks:
            - backend
            - frontend
    nginx:
        image: nginx:1.19.4-alpine
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/certificates:/mycerts
        depends_on:
            - nextcloud
        networks:
            - frontend
networks:
    backend:
    frontend:
