homeassistant:
  name: Home
  latitude: !secret general_latitude
  longitude: !secret general_longitude
  elevation: !secret general_elevation
  unit_system: metric
  time_zone: !secret general_time_zone
  external_url: !secret general_external_url
  internal_url: !secret general_internal_url
  legacy_templates: false
  packages: !include_dir_named config

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: yaml
  resources:
    # Yandex Icons
    - url: /hacsfiles/ha-yandex-icons/yandex-icons.js
      type: module
    # Xiaomi vacuum map
    - url: /local/custom_lovelace/xiaomi_vacuum_map_card/xiaomi-vacuum-map-card.js
      type: module
