
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Yandex Station integration
yandex_station:
  username: !secret yandex_user
  password: !secret yandex_password

# Xiaomi Roborock Sweep one
vacuum:
  - platform: xiaomi_miio
    host: !secret roborock_host
    token: !secret roborock_token

lovelace:
  mode: yaml
  resources:
    # Yandex Icons
    - url: /hacsfiles/ha-yandex-icons/yandex-icons.js
      type: module
